/**
 * Breakthrough Manager OS - Comprehensive Clinical & Operational Seed Data
 * Tailored for Australian NDIS Registered Providers, Allied Health, and PBS Practices.
 */

import {
  Participant,
  RestrictivePracticeProtocol,
  RestrictivePracticeLog,
  IncidentReport,
  RosterShift,
  SOAPCaseNote,
  UserProfile,
} from '../types';

export const INITIAL_USER_PROFILE: UserProfile = {
  id: 'usr-clinician-001',
  name: 'Dr. Sarah Jenkins',
  email: 's.jenkins@breakthroughsupport.org.au',
  role: 'lead_clinician',
  tenantId: 'tenant-breakthrough-vic',
  branchId: 'branch-melbourne-cbd',
  organisationName: 'Breakthrough Support & Positive Behaviour Clinics',
  ndisWorkerScreeningId: 'NDISWC-VIC-8492019',
  ndisWorkerScreeningExpiry: '2028-04-15',
  workingWithChildrenCheckExpiry: '2027-11-20',
  firstAidExpiry: '2026-10-12',
  pbsPractitionerLevel: 'specialist',
  schadsLevel: 6,
  schadsPayPoint: 1,
};

export const INITIAL_PARTICIPANTS: Participant[] = [
  {
    id: 'part-001',
    tenantId: 'tenant-breakthrough-vic',
    ndisNumber: '430891274',
    fullName: 'Liam Alexander Walker',
    preferredName: 'Liam',
    dateOfBirth: '2008-05-14',
    gender: 'Male',
    primaryDiagnosis: 'Autism Spectrum Disorder (Level 3) with High Acuity Sensory Processing Sensitivity',
    secondaryDiagnoses: ['Attention Deficit Hyperactivity Disorder', 'Expressive Language Disorder'],
    mmmZone: 1, // Metropolitan Melbourne
    suburb: 'Hawthorn',
    postcode: '3122',
    state: 'VIC',
    planStartDate: '2026-01-10',
    planEndDate: '2027-01-09',
    totalAllocatedBudget: 184500.0,
    consumedBudget: 62450.0,
    activeBSP: true,
    bspReviewDueDate: '2026-11-15',
    activeRestrictivePracticesCount: 2,
    contactEmergencyName: 'Margaret Walker (Mother & Nominee)',
    contactEmergencyPhone: '0412 884 901',
    behaviourSupportPractitioner: 'Dr. Sarah Jenkins (PBS Specialist)',
    alliedHealthKeyWorker: 'Marcus Vance (Senior OT)',
  },
  {
    id: 'part-002',
    tenantId: 'tenant-breakthrough-vic',
    ndisNumber: '431056722',
    fullName: 'Chloe Mai Nguyen',
    preferredName: 'Chloe',
    dateOfBirth: '1999-11-23',
    gender: 'Female',
    primaryDiagnosis: 'Acquired Brain Injury (ABI) with Dysexecutive Syndrome',
    secondaryDiagnoses: ['Post-Traumatic Stress Disorder', 'Bilateral Upper Limb Spasticity'],
    mmmZone: 4, // Regional Ballarat
    suburb: 'Ballarat Central',
    postcode: '3350',
    state: 'VIC',
    planStartDate: '2025-08-01',
    planEndDate: '2026-07-31',
    totalAllocatedBudget: 142000.0,
    consumedBudget: 98300.0,
    activeBSP: true,
    bspReviewDueDate: '2026-09-30',
    activeRestrictivePracticesCount: 1,
    contactEmergencyName: 'David Nguyen (Brother)',
    contactEmergencyPhone: '0439 123 789',
    behaviourSupportPractitioner: 'Claire Henderson (PBS Proficient)',
    alliedHealthKeyWorker: 'Jessica Taylor (Clinical Psychologist)',
  },
  {
    id: 'part-003',
    tenantId: 'tenant-breakthrough-vic',
    ndisNumber: '439812456',
    fullName: 'Ethan Patrick Davies',
    preferredName: 'Ethan',
    dateOfBirth: '2012-03-08',
    gender: 'Male',
    primaryDiagnosis: 'Intellectual Disability (Moderate) with Severe Oppositional Behaviours',
    secondaryDiagnoses: ['Global Developmental Delay'],
    mmmZone: 6, // Remote Broken Hill/Regional border
    suburb: 'Broken Hill',
    postcode: '2880',
    state: 'NSW',
    planStartDate: '2026-02-01',
    planEndDate: '2027-01-31',
    totalAllocatedBudget: 215000.0,
    consumedBudget: 44200.0,
    activeBSP: true,
    bspReviewDueDate: '2026-12-01',
    activeRestrictivePracticesCount: 1,
    contactEmergencyName: 'Hannah Davies (Guardian)',
    contactEmergencyPhone: '0488 554 219',
    behaviourSupportPractitioner: 'Dr. Sarah Jenkins (PBS Specialist)',
    alliedHealthKeyWorker: 'Tim O’Connor (Speech Pathologist)',
  },
];

export const INITIAL_RESTRICTIVE_PROTOCOLS: RestrictivePracticeProtocol[] = [
  {
    id: 'rp-proto-001',
    tenantId: 'tenant-breakthrough-vic',
    participantId: 'part-001',
    participantName: 'Liam Alexander Walker',
    type: 'environmental',
    description: 'High-acuity keypad egress lock on kitchen pantry containing cleaning solutions and sharp culinary cutlery.',
    rationale: 'Mitigation of fatal ingestion risk following Functional Behaviour Assessment identifying pica impulses under auditory stress.',
    authorisationStatus: 'authorised',
    authorisingBody: 'Victorian Senior Practitioner / Clinical Authorisation Panel',
    authorisationDate: '2025-11-10',
    expiryDate: '2026-11-09',
    reviewDate: '2026-05-10',
    approvedByPanel: true,
    ndisCommissionReportable: true,
    fadingScheduleDescription: 'Transition to unlocked cupboard with high-level shelf placement and visual PECS schedule prompts, fading over 6 months.',
    baselineFrequencyPerWeek: 7,
    currentFrequencyPerWeek: 4,
    targetDateForElimination: '2027-02-01',
    deEscalationPrerequisites: [
      'Offer quiet retreat space and noise-cancelling headphones',
      'Provide weighted lap blanket and tactile sensory pod',
      'Deploy 2-person verbal soothing protocol using low-arousal vocal tone',
    ],
  },
  {
    id: 'rp-proto-002',
    tenantId: 'tenant-breakthrough-vic',
    participantId: 'part-001',
    participantName: 'Liam Alexander Walker',
    type: 'chemical',
    description: 'PRN Risperidone 0.5mg administered strictly in response to prolonged severe self-injurious head banging.',
    rationale: 'Emergency stabilization when non-pharmacological PBS de-escalation strategies have failed and danger of cranial fracture is acute.',
    authorisationStatus: 'authorised',
    authorisingBody: 'Victorian Senior Practitioner (Panel Approved)',
    authorisationDate: '2026-01-15',
    expiryDate: '2027-01-14',
    reviewDate: '2026-07-15',
    approvedByPanel: true,
    ndisCommissionReportable: true,
    fadingScheduleDescription: 'Quarterly psychiatric multidisciplinary review with goal of 50% dosage reduction alongside functional communication replacement skills.',
    baselineFrequencyPerWeek: 3,
    currentFrequencyPerWeek: 1,
    targetDateForElimination: '2027-06-30',
    deEscalationPrerequisites: [
      'Removal of environmental triggers (bright lights, overlapping sirens)',
      'Engagement in deep pressure proprioceptive joint compressions',
      'Offer preferred calming playlist at 60 bpm',
    ],
  },
  {
    id: 'rp-proto-003',
    tenantId: 'tenant-breakthrough-vic',
    participantId: 'part-002',
    participantName: 'Chloe Mai Nguyen',
    type: 'mechanical',
    description: 'Chest harness on motorized wheelchair during transit to prevent uncontrolled forward postural collapse and asphyxiation.',
    rationale: 'Postural support due to ABI-induced loss of trunk control; classified as mechanical restrictive practice during vehicular transport.',
    authorisationStatus: 'authorised',
    authorisingBody: 'Independent Clinical Review Panel & OT Prescription',
    authorisationDate: '2025-09-01',
    expiryDate: '2026-08-31',
    reviewDate: '2026-03-01',
    approvedByPanel: true,
    ndisCommissionReportable: true,
    fadingScheduleDescription: 'Evaluation with physiotherapy for specialized tilt-in-space seating to eliminate harness dependency where clinically feasible.',
    baselineFrequencyPerWeek: 14,
    currentFrequencyPerWeek: 10,
    targetDateForElimination: '2027-01-01',
    deEscalationPrerequisites: ['Ensure wheelchair is parked on level ground', 'Inspect skin integrity around contact belts'],
  },
];

export const INITIAL_RESTRICTIVE_LOGS: RestrictivePracticeLog[] = [
  {
    id: 'rp-log-001',
    tenantId: 'tenant-breakthrough-vic',
    protocolId: 'rp-proto-001',
    participantId: 'part-001',
    participantName: 'Liam Alexander Walker',
    practiceType: 'environmental',
    wasAuthorised: true,
    isReportableToCommission: true,
    escalationRequired24h: false,
    timestampStart: '2026-09-08T11:20:00Z',
    timestampEnd: '2026-09-08T12:05:00Z',
    durationMinutes: 45,
    administeredBy: 'Marcus Vance (Key Worker)',
    witnessedBy: 'Elena Rossi (Support Worker)',
    immediatePrecursors: 'Loud construction noise outside kitchen triggered acute agitation and approach towards sharp knives.',
    lessRestrictiveAlternativesAttempted: [
      'Offered noise-cancelling headphones',
      'Redirected to sensory dark tent',
      'Provided verbal reassurance',
    ],
    participantOutcome: 'Agitation subsided after 35 minutes; returned to calm drawing activity.',
    postIncidentDebriefCompleted: true,
    reportedToCommissionAt: '2026-09-08T14:30:00Z',
    notes: 'Keypad remained engaged for 45 minutes until external noise ceased.',
  },
];

export const INITIAL_INCIDENTS: IncidentReport[] = [
  {
    id: 'inc-2026-001',
    tenantId: 'tenant-breakthrough-vic',
    incidentNumber: 'INC-2026-089',
    participantId: 'part-001',
    participantName: 'Liam Alexander Walker',
    participantNdisNumber: '430891274',
    occurredAt: '2026-09-07T15:45:00Z',
    reportedAt: '2026-09-07T16:10:00Z',
    locationType: 'transit_vehicle',
    locationAddress: 'Burwood Rd & Power St Intersection, Hawthorn VIC 3122',
    category: 'unauthorised_restrictive_practice',
    severity: 'critical_24h',
    is24HourReportable: true,
    ndisCommissionEscalated: true,
    ndisReferenceNumber: 'NDIS-REF-VIC-2026-99381',
    summary: 'Unauthorised physical restraint applied during transport excursion by casual relief worker.',
    detailedDescription: 'During transport in provider vehicle, casual support worker grasped participant by both forearms for 4 minutes to prevent seatbelt unbuckling. Physical restraint was not an authorised practice within participant’s Behaviour Support Plan.',
    immediateActionsTaken: 'Relief worker instructed to release grip immediately. Driver pulled vehicle safely to roadside curb. Participant provided sensory calming bottle. Shift supervisor and Clinical Lead notified within 15 minutes. Relief worker suspended from solo transit duties pending formal re-training.',
    involvedPersons: [
      {
        id: 'inv-01',
        name: 'Liam Alexander Walker',
        role: 'participant',
        isParticipant: true,
        statementTaken: true,
        statementSummary: 'Participant reported distress and feeling frightened during the forearm hold.',
        injuriesSustained: 'Mild transient erythema on wrists; no bruising or skin tears.',
      },
      {
        id: 'inv-02',
        name: 'Jordan Bell',
        role: 'support_worker',
        contactPhone: '0439 123 456',
        statementTaken: true,
        statementSummary: 'Worker stated they panicked when Liam attempted to release the seatbelt clasp while vehicle was in motion.',
      },
      {
        id: 'inv-03',
        name: 'Elena Rostova',
        role: 'witness',
        contactPhone: '0411 987 654',
        statementTaken: true,
        statementSummary: 'Driver confirmed vehicle was brought to a halt safely and relief worker was directed to release hold.',
      },
    ],
    restrictivePracticeApplied: true,
    restrictivePracticeType: 'physical',
    wasRestrictivePracticeApproved: false,
    restrictivePracticeDetails: {
      applied: true,
      type: 'physical',
      wasAuthorisedInBSP: false,
      durationMinutes: 4,
      emergencyCircumstancesRationale: 'Vehicle was in transit; driver felt immediate safety risk existed.',
      lessRestrictiveAlternativesAttempted: ['Verbal redirection', 'Calming sensory prompts'],
    },
    medicalAttentionRequired: false,
    policeContacted: false,
    ambulanceContacted: false,
    escalation: {
      is24HourReportable: true,
      escalationRequired: true,
      escalatedToCommission: true,
      commissionReferenceNumber: 'NDIS-REF-VIC-2026-99381',
      notifiedAt: '2026-09-07T18:30:00Z',
      notifiedBy: 'Dr. Sarah Jenkins (Clinical Lead)',
      statutoryDeadline24h: '2026-09-08T15:45:00Z',
      statutoryDeadline5Day: '2026-09-12T15:45:00Z',
      notificationStatus: 'notified_within_24h',
      commissionPortalSubmissionNotes: 'Section 73Z reportable notification submitted under reference NDIS-REF-VIC-2026-99381.',
    },
    status: 'notified_commission',
    riskRating: 'extreme',
    createdBy: 'Jordan Bell',
    investigatorNotes: 'Priority 24-hour escalation submitted via NDIS Quality & Safeguards Commission Provider Portal at 18:30 AEST. Comprehensive 5-day investigation report being compiled by Clinical Supervisor.',
  },
  {
    id: 'inc-2026-002',
    tenantId: 'tenant-breakthrough-vic',
    incidentNumber: 'INC-2026-090',
    participantId: 'part-002',
    participantName: 'Chloe Mai Nguyen',
    participantNdisNumber: '431056722',
    occurredAt: '2026-09-08T09:15:00Z',
    reportedAt: '2026-09-08T09:40:00Z',
    locationType: 'supported_independent_living',
    locationAddress: '14 Armstrong St North, Ballarat VIC 3350',
    category: 'medication_error',
    severity: 'high_5day',
    is24HourReportable: false,
    ndisCommissionEscalated: false,
    summary: 'Delayed morning anti-spasticity medication by 1.5 hours due to pharmacy delivery hold-up.',
    detailedDescription: 'Baclofen 10mg scheduled for 08:00 was administered at 09:30 following courier re-routing in Ballarat region. No adverse medical symptoms observed.',
    immediateActionsTaken: 'General Practitioner Dr. M. Kelly consulted. Advised to monitor participant for 2 hours. Participant reported mild stiffness which resolved after administration.',
    involvedPersons: [
      {
        id: 'inv-04',
        name: 'Chloe Mai Nguyen',
        role: 'participant',
        isParticipant: true,
        statementTaken: true,
        statementSummary: 'Chloe reported feeling slightly uncomfortable until medication took effect.',
      },
      {
        id: 'inv-05',
        name: 'Sarah O’Connor',
        role: 'support_worker',
        contactPhone: '0422 345 678',
        statementTaken: true,
        statementSummary: 'Logged medication delay on Webster-pak reconciliation sheet and contacted on-call RN.',
      },
    ],
    restrictivePracticeApplied: false,
    wasRestrictivePracticeApproved: false,
    medicalAttentionRequired: true,
    medicalTreatmentDetails: 'GP consulted via telehealth; no hospitalisation required.',
    policeContacted: false,
    ambulanceContacted: false,
    escalation: {
      is24HourReportable: false,
      escalationRequired: false,
      escalatedToCommission: false,
      statutoryDeadline24h: '2026-09-09T09:15:00Z',
      statutoryDeadline5Day: '2026-09-13T09:15:00Z',
      notificationStatus: 'not_applicable',
    },
    status: 'under_investigation',
    riskRating: 'medium',
    createdBy: 'Sarah O’Connor',
    investigatorNotes: 'Pharmacy agreement escalated to ensure reserve 48-hour dose packs are kept in secured branch vault.',
  },
];

export const INITIAL_SHIFTS: RosterShift[] = [
  {
    id: 'shf-001',
    tenantId: 'tenant-breakthrough-vic',
    workerId: 'wrk-101',
    workerName: 'Elena Rossi',
    participantId: 'part-001',
    participantName: 'Liam Alexander Walker',
    startTime: '2026-09-09T08:00:00+10:00',
    endTime: '2026-09-09T14:00:00+10:00',
    schadsLevel: 2,
    schadsPayPoint: 2,
    isBrokenShift: false,
    travelAllowanceEligible: true,
    distanceKm: 18,
    notes: 'Community access & high-acuity sensory regulation session in Hawthorn.',
    complianceAudit: {
      minimumEngagementMet: true,
      engagementHours: 6.0,
      restBreakBetweenShiftsHours: 14.0,
      restBreakCompliant: true,
      overtimeHours: 0,
      brokenShiftAllowanceApplicable: false,
      violations: [],
    },
  },
  {
    id: 'shf-002',
    tenantId: 'tenant-breakthrough-vic',
    workerId: 'wrk-102',
    workerName: 'Jarrod Murphy',
    participantId: 'part-002',
    participantName: 'Chloe Mai Nguyen',
    startTime: '2026-09-09T07:30:00+10:00',
    endTime: '2026-09-09T09:00:00+10:00',
    schadsLevel: 3,
    schadsPayPoint: 1,
    isBrokenShift: true,
    brokenShiftPart: 1,
    travelAllowanceEligible: true,
    distanceKm: 25,
    notes: 'Morning personal care and mobility transfer in Ballarat.',
    complianceAudit: {
      minimumEngagementMet: false, // 1.5h breaches 2.0h minimum
      engagementHours: 1.5,
      restBreakBetweenShiftsHours: 11.5,
      restBreakCompliant: true,
      overtimeHours: 0,
      brokenShiftAllowanceApplicable: true,
      violations: ['Shift duration of 1.5h breaches Fair Work SCHADS Clause 10.5 (2-hour minimum engagement required).'],
    },
  },
  {
    id: 'shf-003',
    tenantId: 'tenant-breakthrough-vic',
    workerId: 'wrk-102',
    workerName: 'Jarrod Murphy',
    participantId: 'part-002',
    participantName: 'Chloe Mai Nguyen',
    startTime: '2026-09-09T16:00:00+10:00',
    endTime: '2026-09-09T20:30:00+10:00',
    schadsLevel: 3,
    schadsPayPoint: 1,
    isBrokenShift: true,
    brokenShiftPart: 2,
    travelAllowanceEligible: false,
    notes: 'Evening meal prep, social participation & bedtime routine.',
    complianceAudit: {
      minimumEngagementMet: true,
      engagementHours: 4.5,
      restBreakBetweenShiftsHours: 7.0, // Broken shift gap is 7h (within 12h span)
      restBreakCompliant: true,
      overtimeHours: 0,
      brokenShiftAllowanceApplicable: true,
      violations: [],
    },
  },
];

export const INITIAL_CASE_NOTES: SOAPCaseNote[] = [
  {
    id: 'note-001',
    tenantId: 'tenant-breakthrough-vic',
    participantId: 'part-001',
    participantName: 'Liam Alexander Walker',
    practitionerId: 'usr-clinician-001',
    practitionerName: 'Dr. Sarah Jenkins',
    sessionDate: '2026-09-08T10:00:00+10:00',
    durationMinutes: 90,
    subjective: 'Participant arrived in a heightened state following loud sirens on road journey. Mother noted sleep disturbance overnight with 3 awakenings.',
    objective: 'Heart rate observed slightly elevated (92 bpm). Liam avoided eye contact, engaged in mild repetitive hand flapping, and made vocal hums. When presented with the tactile sensory wheel, engagement sustained for 14 minutes without self-injurious behaviour.',
    assessment: 'Sensory overload due to auditory overstimulation. Demonstrating improved responsiveness to tactile grounding tools compared to August baseline. No chemical or physical restrictive practices required.',
    plan: '1. Continue fading schedule for kitchen environmental lock. 2. Liaise with school OT regarding acoustic baffles in classroom. 3. Next PBS review scheduled for 15 September.',
    goalsAddressed: [
      { goalId: 'goal-1', goalTitle: 'Sensory Self-Regulation in Public Settings', progressRating: 4 },
      { goalId: 'goal-2', goalTitle: 'Independent Communication using AAC Tablet', progressRating: 3 },
    ],
    restrictivePracticeObserved: true,
    isPiiMasked: true,
    syncedToCloud: true,
    offlineCreated: false,
    timestamp: '2026-09-08T11:45:00Z',
  },
];
